# settings for ldap
spring:
  ldap:
    urls: ldap://vds-test.services.eni.intranet:18389/
    base: dc=pri
    username: cn=adminLDAP-QLIK,ou=guest,o=ea-tree
    password: B3%jUNwb
    embedded:
      base-dn: dc=pri
      credential:
        username: cn=adminLDAP-QLIK,ou=guest,o=ea-tree
        password: B3%jUNwb
      port: 18389
      validation:
        enabled: false